Anime.create!([
  {genre1: "Action", genre2: "Adventure", genre3: "Magic", genre4: "Military", genre5: "Fantasy", e_title: "Fullmetal Alchemist: Brotherhood", j_title: "鋼の錬金術師 FULLMETAL ALCHEMIST", token: "3936"},
  {genre1: "Action", genre2: "Super Power", genre3: "Fantasy", genre4: "Drama", genre5: "", e_title: "Attack on Titan", j_title: "進撃の巨人", token: "7442"},
  {genre1: "Comedy", genre2: "Sci-Fi", genre3: "Mystery", genre4: "Thriller", genre5: "Drama", e_title: "Steins;Gate", j_title: "", token: "5646"},
  {genre1: "Action", genre2: "Adventure", genre3: "Romance", genre4: "Game", genre5: "Fantasy", e_title: "Sword Art Online", j_title: "ソードアート・オンライン", token: "6589"},
  {genre1: "Mystery", genre2: "Supernatural", genre3: "Police", genre4: "Psychological", genre5: "Thriller", e_title: "Death note", j_title: "デスノート", token: "1376"},
  {genre1: "Action", genre2: "Sci-Fi", genre3: "Super Power", genre4: "Military", genre5: "Mecha", e_title: "Code Geass: Lelouch of the Rebellion", j_title: "コードギアス 反逆のルルーシュ", token: "1415"},
  {genre1: "Action", genre2: "Comedy", genre3: "Supernatural", genre4: "School", genre5: "Drama", e_title: "Angel Beats!", j_title: "エンジェルビーツ!", token: "4604", Youtube: "bLuf89VKhkE"},
  {genre1: "Adventure", genre2: "Supernatural", genre3: "Romance", genre4: "Drama", genre5: "", e_title: "Spirited Away", j_title: "千と千尋の神隠し", token: "176"},
  {genre1: "Action", genre2: "Comedy", genre3: "Sci-Fi", genre4: "Mecha", genre5: "", e_title: " Tengen Toppa Gurren Lagann", j_title: "天元突破グレンラガン", token: "1801"},
  {genre1: "Action", genre2: "Adventure", genre3: "Comedy", genre4: "Sci-Fi", genre5: "Space", e_title: "Cowboy Bebop", j_title: "カウボーイビバップ", token: "1"},
  {genre1: "Action", genre2: "Sci-Fi", genre3: "Super Power", genre4: "Military", genre5: "Mecha", e_title: "Code Geass: Lelouch of the Rebellion R2", j_title: "コードギアス 反逆のルルーシュ R2", token: "2634"},
  {genre1: "Action", genre2: "Supernatural", genre3: "Fantasy", genre4: "", genre5: "", e_title: "Fate/Zero", j_title: "フェイト/ゼロ", token: "6028"},
  {genre1: "Action", genre2: "Comedy", genre3: "Super Power", genre4: "School", genre5: "", e_title: "Kill la Kill", j_title: "キルラキル", token: "7712"},
  {genre1: "Comedy", genre2: "Romance", genre3: "School", genre4: "Slice of Life", genre5: "", e_title: "Toradora!", j_title: "とらドラ！", token: "3532"},
  {genre1: "Action", genre2: "Mystery", genre3: "Supernatural", genre4: "Psychological", genre5: "Thriller", e_title: "Mirai Nikki(TV)", j_title: "未来日記", token: "6266", Youtube: "9U0uD-NODhM"},
  {genre1: "Magic", genre2: "Psychological", genre3: "Thriller", genre4: "Mahou Shoujo", genre5: "Drama", e_title: "Puello Magi Madoka Magica", j_title: "魔法少女まどか☆マギカ", token: "5853"},
  {genre1: "Action", genre2: "Mystery", genre3: "Supernatural", genre4: "", genre5: "", e_title: "Durarara!!", j_title: "デュラララ!!", token: "4696", Youtube:"v8cqCapgcaQ"},
  {genre1: "Action", genre2: "Sci-Fi", genre3: "Polics", genre4: "Thriller", genre5: "", e_title: "Psycho-Pass", j_title: "サイコパス", token: "7000"},
  {genre1: "Comedy", genre2: "Mystery", genre3: "Supernatural", genre4: "Romance", genre5: "Ecchi", e_title: "bakemonogatari", j_title: "化物語", token: "3919"},
  {genre1: "Supernatural", genre2: "Romance", genre3: "Fantasy", genre4: "Slice of Life", genre5: "Drama", e_title: "Clannad: After Stroy", j_title: "クラナド　アフターストーリ", token: "3505"},
  {genre1: "Comedy", genre2: "Supernatural", genre3: "Romance", genre4: "School", genre5: "Slice of Life", e_title: "Clannad", j_title: "クラナド", token: "1962"},
  {genre1: "Adventure", genre2: "Comedy", genre3: "Supernatural", genre4: "Ecchi", genre5: "Game", e_title: "No Game No Life", j_title: "ノーゲーム・ノーライフ", token: "7880"},
  {genre1: "Action", genre2: "Adventure", genre3: "Comedy", genre4: "Magic", genre5: "Military", e_title: "Fullmetal Alchemist", j_title: "鋼の錬金術師", token: "100", Youtube:"6jIH-UbMP10"},
  {genre1: "Action", genre2: "Adventure", genre3: "Comedy", genre4: "Supernatural", genre5: "Fantasy", e_title: "Soul Eater", j_title: "ソウルイーター", token: "3128"},
  {genre1:"Drama", genre2:"Horror", genre3:"Thriller", genre4:"", e_title: "Monster", j_title:"モンスター", token:"10", Youtube:"yM0gjM96nxk"},
  {genre1:"Drama", genre2:"Romance", genre3:"", genre4:"", e_title: "Your Lie in April", j_title:"四月は君の嘘", token:"8403", Youtube:"3aL0gDZtFbE"},
  {genre1:"Action", genre2:"Adventure", genre3:"Fantasy", genre4:"", e_title: "Noragami", j_title:"ノラガミ", token:"7881"},
  {genre1:"Action", genre2:"Adventure", genre3:"", genre4:"", e_title: "Hunter x Hunter", j_title:"ハンターハンター", token:"115"}
])
